CREATE TABLE TESTTABLE(ID INTEGER NOT NULL, VALUE VARCHAR(255), PRIMARY KEY (ID) )

INSERT INTO TESTTABLE VALUES(1, 'value')

INSERT INTO ticket VALUES(0, 'contents', '2020-01-31', 'title', 'writer')

;